package dpfm_api_output_formatter

type SDC struct {
	ConnectionKey       string      `json:"connection_key"`
	Result              bool        `json:"result"`
	RedisKey            string      `json:"redis_key"`
	Filepath            string      `json:"filepath"`
	APIStatusCode       int         `json:"api_status_code"`
	RuntimeSessionID    string      `json:"runtime_session_id"`
	BusinessPartnerID   *int        `json:"business_partner"`
	ServiceLabel        string      `json:"service_label"`
	APIType             string      `json:"api_type"`
	Message             interface{} `json:"message"`
	APISchema           string      `json:"api_schema"`
	Accepter            []string    `json:"accepter"`
	Deleted             bool        `json:"deleted"`
	SQLUpdateResult     *bool       `json:"sql_update_result"`
	SQLUpdateError      string      `json:"sql_update_error"`
	SubfuncResult       *bool       `json:"subfunc_result"`
	SubfuncError        string      `json:"subfunc_error"`
	ExconfResult        *bool       `json:"exconf_result"`
	ExconfError         string      `json:"exconf_error"`
	APIProcessingResult *bool       `json:"api_processing_result"`
	APIProcessingError  string      `json:"api_processing_error"`
}

type Message struct {
	Header                            *[]Header                            `json:"Header"`
	HeaderDoc                         *[]HeaderDoc                         `json:"HeaderDoc"`
	Item                              *[]Item                              `json:"Item"`
	ItemComponent                     *[]ItemComponent                     `json:"ItemComponent"`
	ItemComponentDeliveryScheduleLine *[]ItemComponentDeliveryScheduleLine `json:"ItemComponentDeliveryScheduleLine"`
	ItemComponentCosting              *[]ItemComponentCosting              `json:"ItemComponentCosting"`
	ItemOperation                     *[]ItemOperation                     `json:"ItemOperation"`
	ItemOperationComponent            *[]ItemOperationComponent            `json:"ItemOperationComponent"`
	ItemOperationCosting              *[]ItemOperationCosting              `json:"ItemOperationCosting"`
}

type Header struct {
	ProductionOrder                                    int      `json:"ProductionOrder"`
	SupplyChainRelationshipID                          int      `json:"SupplyChainRelationshipID"`
	SupplyChainRelationshipProductionPlantID           int      `json:"SupplyChainRelationshipProductionPlantID"`
	SupplyChainRelationshipDeliveryID                  int      `json:"SupplyChainRelationshipDeliveryID"`
	SupplyChainRelationshipDeliveryPlantID             int      `json:"SupplyChainRelationshipDeliveryPlantID"`
	ProductionOrderType                                string   `json:"ProductionOrderType"`
	Product                                            string   `json:"Product"`
	Buyer                                              int      `json:"Buyer"`
	Seller                                             int      `json:"Seller"`
	OwnerProductionPlantBusinessPartner                int      `json:"OwnerProductionPlantBusinessPartner"`
	OwnerProductionPlant                               string   `json:"OwnerProductionPlant"`
	OwnerProductionPlantStorageLocation                string   `json:"OwnerProductionPlantStorageLocation"`
	DepartureDeliverFromParty                          int      `json:"DepartureDeliverFromParty"`
	DepartureDeliverFromPlant                          string   `json:"DepartureDeliverFromPlant"`
	DepartureDeliverFromPlantStorageLocation           string   `json:"DepartureDeliverFromPlantStorageLocation"`
	DestinationDeliverToParty                          int      `json:"DestinationDeliverToParty"`
	DestinationDeliverToPlant                          string   `json:"DestinationDeliverToPlant"`
	DestinationDeliverToPlantStorageLocation           string   `json:"DestinationDeliverToPlantStorageLocation"`
	ProductBaseUnit                                    string   `json:"ProductBaseUnit"`
	MRPArea                                            *string  `json:"MRPArea"`
	MRPController                                      *string  `json:"MRPController"`
	ProductionVersion                                  *int     `json:"ProductionVersion"`
	BillOfMaterial                                     int      `json:"BillOfMaterial"`
	Operations                                         int      `json:"Operations"`
	ProductionOrderQuantityInBaseUnit                  float32  `json:"ProductionOrderQuantityInBaseUnit"`
	ProductionOrderQuantityInDepartureProductionUnit   float32  `json:"ProductionOrderQuantityInDepartureProductionUnit"`
	ProductionOrderQuantityInDestinationProductionUnit float32  `json:"ProductionOrderQuantityInDestinationProductionUnit"`
	ProductionOrderQuantityInDepartureDeliveryUnit     float32  `json:"ProductionOrderQuantityInDepartureDeliveryUnit"`
	ProductionOrderQuantityInDestinationDeliveryUnit   float32  `json:"ProductionOrderQuantityInDestinationDeliveryUnit"`
	ProductionOrderDepartureProductionUnit             string   `json:"ProductionOrderDepartureProductionUnit"`
	ProductionOrderDestinationProductionUnit           string   `json:"ProductionOrderDestinationProductionUnit"`
	ProductionOrderDepartureDeliveryUnit               string   `json:"ProductionOrderDepartureDeliveryUnit"`
	ProductionOrderDestinationDeliveryUnit             string   `json:"ProductionOrderDestinationDeliveryUnit"`
	ProductionOrderPlannedScrapQtyInBaseUnit           *float32 `json:"ProductionOrderPlannedScrapQtyInBaseUnit"`
	ProductionOrderPlannedStartDate                    string   `json:"ProductionOrderPlannedStartDate"`
	ProductionOrderPlannedStartTime                    string   `json:"ProductionOrderPlannedStartTime"`
	ProductionOrderPlannedEndDate                      string   `json:"ProductionOrderPlannedEndDate"`
	ProductionOrderPlannedEndTime                      string   `json:"ProductionOrderPlannedEndTime"`
	ProductionOrderActualReleaseDate                   *string  `json:"ProductionOrderActualReleaseDate"`
	ProductionOrderActualReleaseTime                   *string  `json:"ProductionOrderActualReleaseTime"`
	ProductionOrderActualStartDate                     *string  `json:"ProductionOrderActualStartDate"`
	ProductionOrderActualStartTime                     *string  `json:"ProductionOrderActualStartTime"`
	ProductionOrderActualEndDate                       *string  `json:"ProductionOrderActualEndDate"`
	ProductionOrderActualEndTime                       *string  `json:"ProductionOrderActualEndTime"`
	PlannedOrder                                       *int     `json:"PlannedOrder"`
	OrderID                                            *int     `json:"OrderID"`
	OrderItem                                          *int     `json:"OrderItem"`
	ProductionOrderHeaderText                          *string  `json:"ProductionOrderHeaderText"`
	CreationDate                                       string   `json:"CreationDate"`
	CreationTime                                       string   `json:"CreationTime"`
	LastChangeDate                                     string   `json:"LastChangeDate"`
	LastChangeTime                                     string   `json:"LastChangeTime"`
	IsReleased                                         *bool    `json:"IsReleased"`
	IsPartiallyConfirmed                               *bool    `json:"IsPartiallyConfirmed"`
	IsConfirmed                                        *bool    `json:"IsConfirmed"`
	IsLocked                                           *bool    `json:"IsLocked"`
	IsCancelled                                        *bool    `json:"IsCancelled"`
	IsMarkedForDeletion                                *bool    `json:"IsMarkedForDeletion"`
}

type HeaderDoc struct {
	ProductionOrder          int     `json:"ProductionOrder"`
	DocType                  string  `json:"DocType"`
	DocVersionID             int     `json:"DocVersionID"`
	DocID                    string  `json:"DocID"`
	FileExtension            string  `json:"FileExtension"`
	FileName                 *string `json:"FileName"`
	FilePath                 *string `json:"FilePath"`
	DocIssuerBusinessPartner *int    `json:"DocIssuerBusinessPartner"`
}

type Item struct {
	ProductionOrder                               int      `json:"ProductionOrder"`
	ProductionOrderItem                           int      `json:"ProductionOrderItem"`
	PrecedingProductionOrderItem                  *int     `json:"PrecedingProductionOrderItem"`
	FollowingProductionOrderItem                  *int     `json:"FollowingProductionOrderItem"`
	SupplyChainRelationshipID                     int      `json:"SupplyChainRelationshipID"`
	SupplyChainRelationshipProductionPlantID      int      `json:"SupplyChainRelationshipProductionPlantID"`
	SupplyChainRelationshipDeliveryID             int      `json:"SupplyChainRelationshipDeliveryID"`
	SupplyChainRelationshipDeliveryPlantID        int      `json:"SupplyChainRelationshipDeliveryPlantID"`
	ProductionOrderType                           string   `json:"ProductionOrderType"`
	Product                                       string   `json:"Product"`
	Buyer                                         int      `json:"Buyer"`
	Seller                                        int      `json:"Seller"`
	ProductionPlantBusinessPartner                int      `json:"ProductionPlantBusinessPartner"`
	ProductionPlant                               string   `json:"ProductionPlant"`
	ProductionPlantStorageLocation                string   `json:"ProductionPlantStorageLocation"`
	DeliverFromParty                              int      `json:"DeliverFromParty"`
	DeliverFromPlant                              string   `json:"DeliverFromPlant"`
	DeliverFromPlantStorageLocation               string   `json:"DeliverFromPlantStorageLocation"`
	DeliverToParty                                int      `json:"DeliverToParty"`
	DeliverToPlant                                string   `json:"DeliverToPlant"`
	DeliverToPlantStorageLocation                 string   `json:"DeliverToPlantStorageLocation"`
	ProductBaseUnit                               string   `json:"ProductBaseUnit"`
	ProductProductionUnit                         string   `json:"ProductProductionUnit"`
	ProductDeliveryUnit                           string   `json:"ProductDeliveryUnit"`
	MRPArea                                       *string  `json:"MRPArea"`
	MRPController                                 *string  `json:"MRPController"`
	ProductionVersion                             *int     `json:"ProductionVersion"`
	ProductionVersionItem                         *int     `json:"ProductionVersionItem"`
	BillOfMaterial                                int      `json:"BillOfMaterial"`
	Operations                                    int      `json:"Operations"`
	ProductionOrderQuantityInBaseUnit             float32  `json:"ProductionOrderQuantityInBaseUnit"`
	ProductionOrderQuantityInProductionUnit       float32  `json:"ProductionOrderQuantityInProductionUnit"`
	ProductionOrderQuantityInDeliveryUnit         float32  `json:"ProductionOrderQuantityInDeliveryUnit"`
	ProductionOrderPlannedScrapQtyInBaseUnit      *float32 `json:"ProductionOrderPlannedScrapQtyInBaseUnit"`
	ProductionOrderMinimumLotSizeQuantity         float32  `json:"ProductionOrderMinimumLotSizeQuantity"`
	ProductionOrderStandardLotSizeQuantity        float32  `json:"ProductionOrderStandardLotSizeQuantity"`
	ProductionOrderMaximumLotSizeQuantity         float32  `json:"ProductionOrderMaximumLotSizeQuantity"`
	ProductionOrderLotSizeRoundingQuantity        *float32 `json:"ProductionOrderLotSizeRoundingQuantity"`
	ProductionOrderLotSizeIsFixed                 *bool    `json:"ProductionOrderLotSizeIsFixed"`
	ProductionOrderPlannedStartDate               string   `json:"ProductionOrderPlannedStartDate"`
	ProductionOrderPlannedStartTime               string   `json:"ProductionOrderPlannedStartTime"`
	ProductionOrderPlannedEndDate                 string   `json:"ProductionOrderPlannedEndDate"`
	ProductionOrderPlannedEndTime                 string   `json:"ProductionOrderPlannedEndTime"`
	ProductionOrderActualReleaseDate              *string  `json:"ProductionOrderActualReleaseDate"`
	ProductionOrderActualReleaseTime              *string  `json:"ProductionOrderActualReleaseTime"`
	ProductionOrderActualStartDate                *string  `json:"ProductionOrderActualStartDate"`
	ProductionOrderActualStartTime                *string  `json:"ProductionOrderActualStartTime"`
	ProductionOrderActualEndDate                  *string  `json:"ProductionOrderActualEndDate"`
	ProductionOrderActualEndTime                  *string  `json:"ProductionOrderActualEndTime"`
	ConfirmedYieldQuantityInBaseUnit              *float32 `json:"ConfirmedYieldQuantityInBaseUnit"`
	ConfirmedYieldQuantityInProductionUnit        *float32 `json:"ConfirmedYieldQuantityInProductionUnit"`
	ScrappedQuantityInBaseUnit                    *float32 `json:"ScrappedQuantityInBaseUnit"`
	PlannedOrder                                  *int     `json:"PlannedOrder"`
	PlannedOrderItem                              *int     `json:"PlannedOrderItem"`
	OrderID                                       *int     `json:"OrderID"`
	OrderItem                                     *int     `json:"OrderItem"`
	ProductIsBatchManagedInProductionPlant        *bool    `json:"ProductIsBatchManagedInProductionPlant"`
	BatchMgmtPolicyInProductionOrder              *string  `json:"BatchMgmtPolicyInProductionOrder"`
	ProductionOrderTargetedBatch                  *string  `json:"ProductionOrderTargetedBatch"`
	ProductionOrderTargetedBatchValidityStartDate *string  `json:"ProductionOrderTargetedBatchValidityStartDate"`
	ProductionOrderTargetedBatchValidityStartTime *string  `json:"ProductionOrderTargetedBatchValidityStartTime"`
	ProductionOrderTargetedBatchValidityEndDate   *string  `json:"ProductionOrderTargetedBatchValidityEndDate"`
	ProductionOrderTargetedBatchValidityEndTime   *string  `json:"ProductionOrderTargetedBatchValidityEndTime"`
	ProductionOrderItemText                       *string  `json:"ProductionOrderItemText"`
	CreationDate                                  string   `json:"CreationDate"`
	CreationTime                                  string   `json:"CreationTime"`
	LastChangeDate                                string   `json:"LastChangeDate"`
	LastChangeTime                                string   `json:"LastChangeTime"`
	IsReleased                                    *bool    `json:"IsReleased"`
	IsPartiallyConfirmed                          *bool    `json:"IsPartiallyConfirmed"`
	IsConfirmed                                   *bool    `json:"IsConfirmed"`
	IsLocked                                      *bool    `json:"IsLocked"`
	IsCancelled                                   *bool    `json:"IsCancelled"`
	IsMarkedForDeletion                           *bool    `json:"IsMarkedForDeletion"`
}

type ItemComponent struct {
	ProductionOrder                                int      `json:"ProductionOrder"`
	ProductionOrderItem                            int      `json:"ProductionOrderItem"`
	BillOfMaterial                                 int      `json:"BillOfMaterial"`
	BillOfMaterialItem                             int      `json:"BillOfMaterialItem"`
	SupplyChainRelationshipID                      int      `json:"SupplyChainRelationshipID"`
	SupplyChainRelationshipDeliveryID              int      `json:"SupplyChainRelationshipDeliveryID"`
	SupplyChainRelationshipDeliveryPlantID         int      `json:"SupplyChainRelationshipDeliveryPlantID"`
	SupplyChainRelationshipStockConfPlantID        int      `json:"SupplyChainRelationshipStockConfPlantID"`
	ProductionPlantBusinessPartner                 int      `json:"ProductionPlantBusinessPartner"`
	ProductionPlant                                string   `json:"ProductionPlant"`
	MRPArea                                        *string  `json:"MRPArea"`
	MRPController                                  *string  `json:"MRPController"`
	ProductionVersion                              *int     `json:"ProductionVersion"`
	ProductionVersionItem                          *int     `json:"ProductionVersionItem"`
	ComponentProduct                               string   `json:"ComponentProduct"`
	ComponentProductBuyer                          int      `json:"ComponentProductBuyer"`
	ComponentProductSeller                         int      `json:"ComponentProductSeller"`
	ComponentProductDeliverToParty                 int      `json:"ComponentProductDeliverToParty"`
	ComponentProductDeliverToPlant                 string   `json:"ComponentProductDeliverToPlant"`
	ComponentProductDeliverFromParty               int      `json:"ComponentProductDeliverFromParty"`
	ComponentProductDeliverFromPlant               string   `json:"ComponentProductDeliverFromPlant"`
	ComponentProductBaseUnit                       string   `json:"ComponentProductBaseUnit"`
	ComponentProductDeliveryUnit                   string   `json:"ComponentProductDeliveryUnit"`
	ComponentProductRequirementDate                string   `json:"ComponentProductRequirementDate"`
	ComponentProductRequirementTime                string   `json:"ComponentProductRequirementTime"`
	ComponentProductRequiredQuantityInBaseUnit     float32  `json:"ComponentProductRequiredQuantityInBaseUnit"`
	ComponentProductRequiredQuantityInDeliveryUnit float32  `json:"ComponentProductRequiredQuantityInDeliveryUnit"`
	ComponentProductPlannedScrapInPercent          *float32 `json:"ComponentProductPlannedScrapInPercent"`
	ComponentProductIsMarkedForBackflush           *bool    `json:"ComponentProductIsMarkedForBackflush"`
	StockConfirmationBusinessPartner               int      `json:"StockConfirmationBusinessPartner"`
	StockConfirmationPlant                         string   `json:"StockConfirmationPlant"`
	StockConfirmationPlantStorageLocation          string   `json:"StockConfirmationPlantStorageLocation"`
	PlannedOrder                                   *int     `json:"PlannedOrder"`
	PlannedOrderItem                               *int     `json:"PlannedOrderItem"`
	BillOfMaterialItemText                         *string  `json:"BillOfMaterialItemText"`
	ComponentProductBatch                          *string  `json:"ComponentProductBatch"`
	ComponentProductBatchValidityStartDate         *string  `json:"ComponentProductBatchValidityStartDate"`
	ComponentProductBatchValidityStartTime         *string  `json:"ComponentProductBatchValidityStartTime"`
	ComponentProductBatchValidityEndDate           *string  `json:"ComponentProductBatchValidityEndDate"`
	ComponentProductBatchValidityEndTime           *string  `json:"ComponentProductBatchValidityEndTime"`
	ComponentProductCostingPolicy                  *string  `json:"ComponentProductCostingPolicy"`
	ComponentProductPriceUnitQty                   *int     `json:"ComponentProductPriceUnitQty"`
	ComponentProductStandardPrice                  *float32 `json:"ComponentProductStandardPrice"`
	ComponentProductMovingAveragePrice             *float32 `json:"ComponentProductMovingAveragePrice"`
	ComponentProductWithdrawnQuantity              *float32 `json:"ComponentProductWithdrawnQuantity"`
	CreationDate                                   string   `json:"CreationDate"`
	CreationTime                                   string   `json:"CreationTime"`
	LastChangeDate                                 string   `json:"LastChangeDate"`
	LastChangeTime                                 string   `json:"LastChangeTime"`
	ComponentProductAvailabilityIsNotChecked       *bool    `json:"ComponentProductAvailabilityIsNotChecked"`
	IsReleased                                     *bool    `json:"IsReleased"`
	IsLocked                                       *bool    `json:"IsLocked"`
	IsCancelled                                    *bool    `json:"IsCancelled"`
	IsMarkedForDeletion                            *bool    `json:"IsMarkedForDeletion"`
}

type ItemComponentDeliveryScheduleLine struct {
	ProductionOrder                            int      `json:"ProductionOrder"`
	ProductionOrderItem                        int      `json:"ProductionOrderItem"`
	BillOfMaterial                             int      `json:"BillOfMaterial"`
	BillOfMaterialItem                         int      `json:"BillOfMaterialItem"`
	ScheduleLine                               int      `json:"ScheduleLine"`
	SupplyChainRelationshipID                  int      `json:"SupplyChainRelationshipID"`
	SupplyChainRelationshipStockConfPlantID    int      `json:"SupplyChainRelationshipStockConfPlantID"`
	ComponentProduct                           string   `json:"ComponentProduct"`
	StockConfirmationBusinessPartner           int      `json:"StockConfirmationBusinessPartner"`
	StockConfirmationPlant                     string   `json:"StockConfirmationPlant"`
	StockConfirmationPlantTimeZone             *string  `json:"StockConfirmationPlantTimeZone"`
	ComponentProductBatch                      *string  `json:"ComponentProductBatch"`
	ComponentProductBatchValidityStartDate     *string  `json:"ComponentProductBatchValidityStartDate"`
	ComponentProductBatchValidityStartTime     *string  `json:"ComponentProductBatchValidityStartTime"`
	ComponentProductBatchValidityEndDate       *string  `json:"ComponentProductBatchValidityEndDate"`
	ComponentProductBatchValidityEndTime       *string  `json:"ComponentProductBatchValidityEndTime"`
	RequestedDeliveryDate                      string   `json:"RequestedDeliveryDate"`
	RequestedDeliveryTime                      string   `json:"RequestedDeliveryTime"`
	ConfirmedDeliveryDate                      *string  `json:"ConfirmedDeliveryDate"`
	ConfirmedDeliveryTime                      *string  `json:"ConfirmedDeliveryTime"`
	OriginalRequiredQuantityInBaseUnit         float32  `json:"OriginalRequiredQuantityInBaseUnit"`
	ConfirmedQuantityByPDTAvailCheckInBaseUnit *float32 `json:"ConfirmedQuantityByPDTAvailCheckInBaseUnit"`
	OpenConfirmedQuantityInBaseUnit            *float32 `json:"OpenConfirmedQuantityInBaseUnit"`
	DeliveredQuantityInBaseUnit                *float32 `json:"DeliveredQuantityInBaseUnit"`
	UndeliveredQuantityInBaseUnit              *float32 `json:"UndeliveredQuantityInBaseUnit"`
	StockIsFullyConfirmed                      *bool    `json:"StockIsFullyConfirmed"`
	PlusMinusFlag                              *string  `json:"PlusMinusFlag"`
	ItemScheduleLineDeliveryBlockStatus        *bool    `json:"ItemScheduleLineDeliveryBlockStatus"`
	CreationDate                               string   `json:"CreationDate"`
	CreationTime                               string   `json:"CreationTime"`
	LastChangeDate                             string   `json:"LastChangeDate"`
	LastChangeTime                             string   `json:"LastChangeTime"`
	IsReleased                                 *bool    `json:"IsReleased"`
	IsLocked                                   *bool    `json:"IsLocked"`
	IsCancelled                                *bool    `json:"IsCancelled"`
	IsMarkedForDeletion                        *bool    `json:"IsMarkedForDeletion"`
}

type ItemComponentCosting struct {
	ProductionOrder     int     `json:"ProductionOrder"`
	ProductionOrderItem int     `json:"ProductionOrderItem"`
	BillOfMaterial      int     `json:"BillOfMaterial"`
	BillOfMaterialItem  int     `json:"BillOfMaterialItem"`
	Currency            string  `json:"Currency"`
	CostingAmount       float32 `json:"CostingAmount"`
	CreationDate        string  `json:"CreationDate"`
	CreationTime        string  `json:"CreationTime"`
	LastChangeDate      string  `json:"LastChangeDate"`
	LastChangeTime      string  `json:"LastChangeTime"`
	IsReleased          *bool   `json:"IsReleased"`
	IsLocked            *bool   `json:"IsLocked"`
	IsCancelled         *bool   `json:"IsCancelled"`
	IsMarkedForDeletion *bool   `json:"IsMarkedForDeletion"`
}

type ItemDoc struct {
	ProductionOrder          int     `json:"ProductionOrder"`
	ProductionOrderItem      int     `json:"ProductionOrderItem"`
	DocType                  string  `json:"DocType"`
	DocVersionID             int     `json:"DocVersionID"`
	DocID                    string  `json:"DocID"`
	FileExtension            string  `json:"FileExtension"`
	FileName                 *string `json:"FileName"`
	FilePath                 *string `json:"FilePath"`
	DocIssuerBusinessPartner *int    `json:"DocIssuerBusinessPartner"`
}

type ItemOperation struct {
	ProductionOrder                                 int      `json:"ProductionOrder"`
	ProductionOrderItem                             int      `json:"ProductionOrderItem"`
	Operations                                      int      `json:"Operations"`
	OperationsItem                                  int      `json:"OperationsItem"`
	OperationID                                     int      `json:"OperationID"`
	OperationType                            		string   `json:"OperationType"`
	SupplyChainRelationshipID                       int      `json:"SupplyChainRelationshipID"`
	SupplyChainRelationshipDeliveryID               int      `json:"SupplyChainRelationshipDeliveryID"`
	SupplyChainRelationshipDeliveryPlantID          int      `json:"SupplyChainRelationshipDeliveryPlantID"`
	SupplyChainRelationshipProductionPlantID        int      `json:"SupplyChainRelationshipProductionPlantID"`
	Product                                         string   `json:"Product"`
	Buyer                                           int      `json:"Buyer"`
	Seller                                          int      `json:"Seller"`
	DeliverFromParty                                int      `json:"DeliverFromParty"`
	DeliverFromPlant                                string   `json:"DeliverFromPlant"`
	DeliverToParty                                  int      `json:"DeliverToParty"`
	DeliverToPlant                                  string   `json:"DeliverToPlant"`
	ProductionPlantBusinessPartner                  int      `json:"ProductionPlantBusinessPartner"`
	ProductionPlant                                 string   `json:"ProductionPlant"`
	MRPArea                                         *string  `json:"MRPArea"`
	MRPController                                   *string  `json:"MRPController"`
	ProductionVersion                               *int     `json:"ProductionVersion"`
	ProductionVersionItem                           *int     `json:"ProductionVersionItem"`
	Sequence                                        int      `json:"Sequence"`
	SequenceText                                    *string  `json:"SequenceText"`
	OperationText                                   string   `json:"OperationText"`
	ProductBaseUnit                                 string   `json:"ProductBaseUnit"`
	ProductProductionUnit                           string   `json:"ProductProductionUnit"`
	ProductOperationUnit                            string   `json:"ProductOperationUnit"`
	ProductDeliveryUnit                             string   `json:"ProductDeliveryUnit"`
	StandardLotSizeQuantity                         float32  `json:"StandardLotSizeQuantity"`
	MinimumLotSizeQuantity                          float32  `json:"MinimumLotSizeQuantity"`
	MaximumLotSizeQuantity                          float32  `json:"MaximumLotSizeQuantity"`
	OperationPlannedQuantityInBaseUnit              float32  `json:"OperationPlannedQuantityInBaseUnit"`
	OperationPlannedQuantityInProductionUnit        float32  `json:"OperationPlannedQuantityInProductionUnit"`
	OperationPlannedQuantityInOperationUnit         float32  `json:"OperationPlannedQuantityInOperationUnit"`
	OperationPlannedQuantityInDeliveryUnit          float32  `json:"OperationPlannedQuantityInDeliveryUnit"`
	OperationPlannedScrapInPercent                  *float32 `json:"OperationPlannedScrapInPercent"`
	ResponsiblePlannerGroup                         *string  `json:"ResponsiblePlannerGroup"`
	PlainLongText                                   *string  `json:"PlainLongText"`
	WorkCenter                                      int      `json:"WorkCenter"`
	CapacityCategory                                *string  `json:"CapacityCategory"`
	OperationCostingRelevancyType                   *string  `json:"OperationCostingRelevancyType"`
	OperationSetupType                              *string  `json:"OperationSetupType"`
	OperationSetupGroupCategory                     *string  `json:"OperationSetupGroupCategory"`
	OperationSetupGroup                             *string  `json:"OperationSetupGroup"`
	MaximumWaitDuration                             *float32 `json:"MaximumWaitDuration"`
	StandardWaitDuration                            *float32 `json:"StandardWaitDuration"`
	MinimumWaitDuration                             *float32 `json:"MinimumWaitDuration"`
	WaitDurationUnit                                *string  `json:"WaitDurationUnit"`
	MaximumQueueDuration                            *float32 `json:"MaximumQueueDuration"`
	StandardQueueDuration                           *float32 `json:"StandardQueueDuration"`
	MinimumQueueDuration                            *float32 `json:"MinimumQueueDuration"`
	QueueDurationUnit                               *string  `json:"QueueDurationUnit"`
	MaximumMoveDuration                             *float32 `json:"MaximumMoveDuration"`
	StandardMoveDuration                            *float32 `json:"StandardMoveDuration"`
	MinimumMoveDuration                             *float32 `json:"MinimumMoveDuration"`
	MoveDurationUnit                                *string  `json:"MoveDurationUnit"`
	StandardDeliveryDuration                        *float32 `json:"StandardDeliveryDuration"`
	StandardDeliveryDurationUnit                    *string  `json:"StandardDeliveryDurationUnit"`
	CostElement                                     *string  `json:"CostElement"`
	OperationErlstSchedldExecStrtDte                *string  `json:"OperationErlstSchedldExecStrtDte"`
	OperationErlstSchedldExecStrtTme                *string  `json:"OperationErlstSchedldExecStrtTme"`
	OperationErlstSchedldExecEndDte                 *string  `json:"OperationErlstSchedldExecEndDte"`
	OperationErlstSchedldExecEndTme                 *string  `json:"OperationErlstSchedldExecEndTme"`
	OperationActualExecutionStartDate               *string  `json:"OperationActualExecutionStartDate"`
	OperationActualExecutionStartTime               *string  `json:"OperationActualExecutionStartTime"`
	OperationActualExecutionEndDate                 *string  `json:"OperationActualExecutionEndDate"`
	OperationActualExecutionEndTime                 *string  `json:"OperationActualExecutionEndTime"`
	OperationConfirmedYieldQuantityInBaseUnit       *float32 `json:"OperationConfirmedYieldQuantityInBaseUnit"`
	OperationConfirmedYieldQuantityInProductionUnit *float32 `json:"OperationConfirmedYieldQuantityInProductionUnit"`
	OperationConfirmedYieldQuantityInOperationUnit  *float32 `json:"OperationConfirmedYieldQuantityInOperationUnit"`
	CreationDate                                    string   `json:"CreationDate"`
	CreationTime                                    string   `json:"CreationTime"`
	LastChangeDate                                  string   `json:"LastChangeDate"`
	LastChangeTime                                  string   `json:"LastChangeTime"`
	IsReleased                                      *bool    `json:"IsReleased"`
	IsPartiallyConfirmed                            *bool    `json:"IsPartiallyConfirmed"`
	IsConfirmed                                     *bool    `json:"IsConfirmed"`
	IsLocked                                        *bool    `json:"IsLocked"`
	IsCancelled                                     *bool    `json:"IsCancelled"`
	IsMarkedForDeletion                             *bool    `json:"IsMarkedForDeletion"`
}

type ItemOperationComponent struct {
	ProductionOrder                                          int      `json:"ProductionOrder"`
	ProductionOrderItem                                      int      `json:"ProductionOrderItem"`
	Operations                                               int      `json:"Operations"`
	OperationsItem                                           int      `json:"OperationsItem"`
	OperationID                                              int      `json:"OperationID"`
	BillOfMaterial                                           int      `json:"BillOfMaterial"`
	BillOfMaterialItem                                       int      `json:"BillOfMaterialItem"`
	SupplyChainRelationshipID                                int      `json:"SupplyChainRelationshipID"`
	SupplyChainRelationshipDeliveryID                        int      `json:"SupplyChainRelationshipDeliveryID"`
	SupplyChainRelationshipDeliveryPlantID                   int      `json:"SupplyChainRelationshipDeliveryPlantID"`
	ProductionPlantBusinessPartner                           int      `json:"ProductionPlantBusinessPartner"`
	ProductionPlant                                          string   `json:"ProductionPlant"`
	ComponentProduct                                         string   `json:"ComponentProduct"`
	ComponentProductBuyer                                    int      `json:"ComponentProductBuyer"`
	ComponentProductSeller                                   int      `json:"ComponentProductSeller"`
	ComponentProductDeliverToParty                           int      `json:"ComponentProductDeliverToParty"`
	ComponentProductDeliverToPlant                           string   `json:"ComponentProductDeliverToPlant"`
	ComponentProductDeliverFromParty                         int      `json:"ComponentProductDeliverFromParty"`
	ComponentProductDeliverFromPlant                         string   `json:"ComponentProductDeliverFromPlant"`
	ComponentProductDeliverToPartyInOperation                int      `json:"ComponentProductDeliverToPartyInOperation"`
	ComponentProductDeliverToPlantInOperation                string   `json:"ComponentProductDeliverToPlantInOperation"`
	ComponentProductDeliverFromPartyInOperation              int      `json:"ComponentProductDeliverFromPartyInOperation"`
	ComponentProductDeliverFromPlantInOperation              string   `json:"ComponentProductDeliverFromPlantInOperation"`
	ComponentProductRequirementDateInOperation               string   `json:"ComponentProductRequirementDateInOperation"`
	ComponentProductRequirementTimeInOperation               string   `json:"ComponentProductRequirementTimeInOperation"`
	ComponentProductPlannedQuantityInBaseUnitInOperation     float32  `json:"ComponentProductPlannedQuantityInBaseUnitInOperation"`
	ComponentProductPlannedQuantityInDeliveryUnitInOperation float32  `json:"ComponentProductPlannedQuantityInDeliveryUnitInOperation"`
	ComponentProductPlannedScrapInPercentInOperation         *float32 `json:"ComponentProductPlannedScrapInPercentInOperation"`
	ComponentProductBaseUnit                                 string   `json:"ComponentProductBaseUnit"`
	ComponentProductDeliveryUnit                             string   `json:"ComponentProductDeliveryUnit"`
	ComponentProductIsMarkedForBackflush                     *bool    `json:"ComponentProductIsMarkedForBackflush"`
	MRPArea                                                  *string  `json:"MRPArea"`
	MRPController                                            *string  `json:"MRPController"`
	ProductionVersion                                        *int     `json:"ProductionVersion"`
	ProductionVersionItem                                    *int     `json:"ProductionVersionItem"`
	ComponentProductReservation                              *int     `json:"ComponentProductReservation"`
	ComponentProductReservationItem                          *int     `json:"ComponentProductReservationItem"`
	CreationDate                                             string   `json:"CreationDate"`
	CreationTime                                             string   `json:"CreationTime"`
	LastChangeDate                                           string   `json:"LastChangeDate"`
	LastChangeTime                                           string   `json:"LastChangeTime"`
	IsReleased                                               *bool    `json:"IsReleased"`
	IsLocked                                                 *bool    `json:"IsLocked"`
	IsCancelled                                              *bool    `json:"IsCancelled"`
	IsMarkedForDeletion                                      *bool    `json:"IsMarkedForDeletion"`
}

type ItemOperationCosting struct {
	ProductionOrder     int     `json:"ProductionOrder"`
	ProductionOrderItem int     `json:"ProductionOrderItem"`
	Operations          int     `json:"Operations"`
	OperationsItem      int     `json:"OperationsItem"`
	OperationID         int     `json:"OperationID"`
	Currency            string  `json:"Currency"`
	CostingAmount       float32 `json:"CostingAmount"`
	CreationDate        string  `json:"CreationDate"`
	CreationTime        string  `json:"CreationTime"`
	LastChangeDate      string  `json:"LastChangeDate"`
	LastChangeTime      string  `json:"LastChangeTime"`
	IsReleased          *bool   `json:"IsReleased"`
	IsLocked            *bool   `json:"IsLocked"`
	IsCancelled         *bool   `json:"IsCancelled"`
	IsMarkedForDeletion *bool   `json:"IsMarkedForDeletion"`
}
